<?php
/**
 * Knit Pay Reports – PDF Exporter
 *
 * Generates branded PDF reports using setasign/fpdf (v1.9).
 * Extends FPDF directly — no InvoicePrinter dependency.
 *
 * @package KnitPay\Reports\Exporter
 */

namespace KnitPay\Reports\Exporter;

use FPDF;
use KnitPay\Reports\ReportsApiHelper;
use Pronamic\WordPress\Money\Currencies;

class PdfExporter extends FPDF {

	private string $report_type;
	private string $date_range_label;
	private array $chart_images;

	private const COLOR_PRIMARY    = [ 34, 113, 177 ];
	private const COLOR_SUCCESS    = [ 0, 163, 42 ];
	private const COLOR_WARNING    = [ 219, 166, 23 ];
	private const COLOR_DANGER     = [ 214, 54, 56 ];
	private const COLOR_LIGHT_BG   = [ 246, 247, 249 ];
	private const COLOR_BORDER     = [ 200, 200, 200 ];
	private const COLOR_TEXT       = [ 30, 30, 30 ];
	private const COLOR_TEXT_LIGHT = [ 120, 120, 120 ];

	public function __construct( string $report_type, string $date_range_label, array $chart_images = [] ) {
		parent::__construct( 'P', 'mm', 'A4' );
		$this->report_type      = $report_type;
		$this->date_range_label = $date_range_label;
		$this->chart_images     = $chart_images;

		$this->SetAutoPageBreak( true, 20 );
		$this->SetMargins( 15, 15, 15 );
		$this->AliasNbPages();

		$this->SetTitle( $this->get_report_title() );
		$this->SetAuthor( get_bloginfo( 'name' ) );
		$this->SetCreator( 'Knit Pay' );
	}

	public function header(): void {
		$this->SetFont( 'Helvetica', 'B', 10 );
		$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
		$this->Cell( 0, 6, 'Knit Pay Reports', 0, 0, 'L' );
		$this->Cell( 0, 6, get_bloginfo( 'name' ), 0, 1, 'R' );

		$this->SetDrawColor( ...self::COLOR_PRIMARY );
		$this->SetLineWidth( 0.5 );
		$this->Line( 15, 21, $this->GetPageWidth() - 15, 21 );
		$this->Ln( 8 );
	}

	public function footer(): void {
		$this->SetY( -15 );
		$this->SetFont( 'Helvetica', 'I', 7 );
		$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
		/* translators: 1: Current page number, 2: Total number of pages */
		$this->Cell( 0, 10, sprintf( __( 'Page %1$d of %2$s', 'knit-pay-lang' ), $this->PageNo(), '{nb}' ), 0, 0, 'C' );
		$this->SetY( -10 );
		$this->Cell( 0, 5, __( 'Generated by Knit Pay', 'knit-pay-lang' ) . ' - ' . gmdate( 'Y-m-d H:i' ), 0, 0, 'R' );
	}

	public function generate( array $data ): string {
		$this->AddPage();
		$this->render_title_section();

		switch ( $this->report_type ) {
			case 'overview':
				$this->render_overview( $data );
				break;
			case 'transactions':
				$this->render_transactions( $data );
				break;
			case 'gateway-performance':
				$this->render_gateway_performance( $data );
				break;
			case 'payment-methods':
				$this->render_payment_methods( $data );
				break;
			case 'sources':
				$this->render_sources( $data );
				break;
			case 'refunds':
				$this->render_refunds( $data );
				break;
		}

		$this->render_chart_images();

		return $this->Output( 'S' );
	}

	private function get_report_title(): string {
		$titles = [
			'overview'            => __( 'Overview Report', 'knit-pay-lang' ),
			'transactions'        => __( 'Payments Report', 'knit-pay-lang' ),
			'gateway-performance' => __( 'Gateways Report', 'knit-pay-lang' ),
			'payment-methods'     => __( 'Payment Methods Report', 'knit-pay-lang' ),
			'sources'             => __( 'Integrations Report', 'knit-pay-lang' ),
			'refunds'             => __( 'Refunds Report', 'knit-pay-lang' ),
		];
		return $titles[ $this->report_type ] ?? __( 'Report', 'knit-pay-lang' );
	}

	private function render_title_section(): void {
		$this->SetFont( 'Helvetica', 'B', 18 );
		$this->SetTextColor( ...self::COLOR_PRIMARY );
		$this->Cell( 0, 12, $this->get_report_title(), 0, 1, 'L' );

		$this->SetFont( 'Helvetica', '', 10 );
		$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
		$this->Cell( 0, 6, $this->date_range_label, 0, 1, 'L' );
		$this->Ln( 4 );
	}

	private function render_kpi_cards( array $kpis ): void {
		$cols      = count( $kpis );
		$usable    = $this->GetPageWidth() - 30;
		$gap       = 4;
		$card_w    = ( $usable - ( $cols - 1 ) * $gap ) / $cols;
		$max_lines = 0;
		foreach ( $kpis as $kpi ) {
			$line_count = substr_count( (string) $kpi['value'], "\n" ) + 1;
			$max_lines  = max( $max_lines, $line_count );
		}
		$card_h  = max( 28, 12 + ( $max_lines * 5 ) );
		$start_x = 15;

		$y = $this->GetY();

		foreach ( $kpis as $i => $kpi ) {
			$x = $start_x + $i * ( $card_w + $gap );

			$this->SetFillColor( ...self::COLOR_LIGHT_BG );
			$this->Rect( $x, $y, $card_w, $card_h, 'F' );

			$border_color = $kpi['color'] ?? self::COLOR_PRIMARY;
			$this->SetDrawColor( ...$border_color );
			$this->SetLineWidth( 1.2 );
			$this->Line( $x, $y, $x, $y + $card_h );

			$this->SetXY( $x + 4, $y + 3 );
			$this->SetFont( 'Helvetica', '', 7 );
			$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
			$this->Cell( $card_w - 8, 4, $kpi['label'], 0, 2 );

			$this->SetFont( 'Helvetica', 'B', 9 );
			$this->SetTextColor( ...self::COLOR_TEXT );
			$this->SetXY( $x + 4, $this->GetY() );
			$this->render_kpi_value_lines( $kpi['value'], $card_w - 8, 5 );
		}

		$this->SetY( $y + $card_h + 6 );
	}

	private function render_section_title( string $title ): void {
		$this->Ln( 2 );
		$this->SetFont( 'Helvetica', 'B', 11 );
		$this->SetTextColor( ...self::COLOR_PRIMARY );
		$this->Cell( 0, 8, $title, 0, 1, 'L' );

		$this->SetDrawColor( ...self::COLOR_BORDER );
		$this->SetLineWidth( 0.2 );
		$this->Line( 15, $this->GetY(), $this->GetPageWidth() - 15, $this->GetY() );
		$this->Ln( 3 );
	}

	private function render_table( array $headers, array $rows, array $col_widths, array $aligns = [] ): void {
		$usable   = $this->GetPageWidth() - 30;
		$row_h    = 7;
		$header_h = 8;

		if ( empty( $aligns ) ) {
			$aligns = array_fill( 0, count( $headers ), 'L' );
		}

		$this->check_page_break( $header_h + min( 3, count( $rows ) ) * $row_h );

		$this->SetFillColor( ...self::COLOR_PRIMARY );
		$this->SetTextColor( 255, 255, 255 );
		$this->SetFont( 'Helvetica', 'B', 8 );

		foreach ( $headers as $i => $header ) {
			$this->Cell( $col_widths[ $i ], $header_h, $header, 1, 0, $aligns[ $i ], true );
		}
		$this->Ln();

		$this->SetTextColor( ...self::COLOR_TEXT );
		$this->SetFont( 'Helvetica', '', 8 );

		foreach ( $rows as $ri => $row ) {
			$this->check_page_break( $row_h );

			if ( 0 === $ri % 2 ) {
				$this->SetFillColor( ...self::COLOR_LIGHT_BG );
			} else {
				$this->SetFillColor( 255, 255, 255 );
			}

			foreach ( $row as $ci => $cell ) {
				$this->Cell( $col_widths[ $ci ], $row_h, $this->truncate_cell( (string) $cell, $col_widths[ $ci ] ), 1, 0, $aligns[ $ci ] ?? 'L', true );
			}
			$this->Ln();
		}
		$this->Ln( 4 );
	}

	private function check_page_break( float $needed_height ): void {
		if ( $this->GetY() + $needed_height > $this->GetPageHeight() - 25 ) {
			$this->AddPage();
		}
	}

	private function render_kpi_value_lines( string $value, float $width, float $line_h ): void {
		$lines   = explode( "\n", $value );
		$start_x = $this->GetX();

		foreach ( $lines as $line ) {
			$parts = explode( ' ', $line, 2 );

			if ( 2 === count( $parts ) ) {
				// Multi-currency line: fixed-width code column + right-aligned amount column.
				$code_col_w = 16;
				$amt_col_w  = max( 10, $width - $code_col_w );
				$this->SetXY( $start_x, $this->GetY() );
				$this->Cell( $code_col_w, $line_h, $parts[0], 0, 0, 'L' );
				$this->Cell( $amt_col_w, $line_h, $parts[1], 0, 0, 'R' );
				$this->SetXY( $start_x, $this->GetY() + $line_h );
			} else {
				// Single value line.
				$this->SetXY( $start_x, $this->GetY() );
				$this->Cell( $width, $line_h, $line, 0, 0, 'L' );
				$this->SetXY( $start_x, $this->GetY() + $line_h );
			}
		}
	}

	private function format_multi_currency( array $amounts_by_currency ): string {
		if ( empty( $amounts_by_currency ) ) {
			return '0';
		}

		$parts = [];
		foreach ( $amounts_by_currency as $cur => $amt ) {
			$parts[] = $cur . ' ' . $this->format_amount_only( (float) $amt, $cur );
		}
		return implode( "\n", $parts );
	}

	private function format_amount_only( float $amount, string $currency ): string {
		$currency_obj = Currencies::get_currency( $currency );
		$decimals     = $currency_obj->get_number_decimals();

		return number_format( $amount, $decimals );
	}

	private function format_currency_amount( float $amount, string $currency ): string {
		$currency_obj = Currencies::get_currency( $currency );
		$decimals     = $currency_obj->get_number_decimals();

		return $currency . ' ' . number_format( $amount, $decimals );
	}

	private function truncate_cell( string $text, float $col_width ): string {
		$max_chars = max( 3, (int) ( $col_width / 1.8 ) );
		$text      = $this->sanitize_text( $text );
		if ( mb_strlen( $text ) > $max_chars ) {
			return mb_substr( $text, 0, $max_chars - 2 ) . '..';
		}
		return $text;
	}

	private array $sanitize_cache = [];

	private function sanitize_text( string $text ): string {
		if ( isset( $this->sanitize_cache[ $text ] ) ) {
			return $this->sanitize_cache[ $text ];
		}

		$converted = iconv( 'UTF-8', 'windows-1252//TRANSLIT//IGNORE', $text );
		if ( false !== $converted ) {
			$this->sanitize_cache[ $text ] = $converted;
			return $converted;
		}

		$fallback = iconv( 'UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $text );
		if ( false !== $fallback ) {
			$this->sanitize_cache[ $text ] = $fallback;
			return $fallback;
		}

		// Strip unencodable characters to prevent FPDF crashes.
		$stripped                      = preg_replace( '/[^\x20-\x7E]/', '', $text ) ?? '';
		$this->sanitize_cache[ $text ] = $stripped;
		return $stripped;
	}

	private function render_overview( array $data ): void {
		$kpis = [
			[
				'label' => __( 'Total Revenue', 'knit-pay-lang' ),
				'value' => $this->format_multi_currency( $data['revenue_by_currency'] ?? [] ),
				'color' => self::COLOR_SUCCESS,
			],
			[
				'label' => __( 'Total Payments', 'knit-pay-lang' ),
				'value' => number_format( (float) ( $data['total_count'] ?? 0 ) ),
				'color' => self::COLOR_PRIMARY,
			],
			[
				'label' => __( 'Success Rate (incl. partial refunds)', 'knit-pay-lang' ),
				'value' => ( $data['success_rate'] ?? 0 ) . '%',
				'color' => ( $data['success_rate'] ?? 0 ) >= 80 ? self::COLOR_SUCCESS : self::COLOR_WARNING,
			],
			[
				'label' => __( 'Avg. Payment', 'knit-pay-lang' ),
				'value' => $this->format_multi_currency( $data['avg_amount_by_currency'] ?? [] ),
				'color' => self::COLOR_PRIMARY,
			],
		];
		$this->render_kpi_cards( $kpis );

		$status_breakdown = $data['status_breakdown'] ?? [];
		if ( ! empty( $status_breakdown ) ) {
			$this->render_section_title( __( 'Status Distribution', 'knit-pay-lang' ) );
			$status_map = ReportsApiHelper::get_status_map();
			$headers    = [ __( 'Status', 'knit-pay-lang' ), __( 'Count', 'knit-pay-lang' ) ];
			$rows       = [];
			$widths     = [ 90, 90 ];
			foreach ( $status_breakdown as $status => $count ) {
				$rows[] = [ $status_map[ $status ] ?? $status, number_format( (int) $count ) ];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R' ] );
		}

		$top_gateways = $data['top_gateways'] ?? [];
		if ( ! empty( $top_gateways ) ) {
			$this->render_section_title( __( 'Top Gateways', 'knit-pay-lang' ) );
			$headers = [ __( 'Gateway', 'knit-pay-lang' ), __( 'Success / Total', 'knit-pay-lang' ), __( 'Success Rate', 'knit-pay-lang' ), __( 'Revenue', 'knit-pay-lang' ) ];
			$rows    = [];
			$widths  = [ 50, 30, 30, 70 ];
			foreach ( $top_gateways as $gw ) {
				$rows[] = [
					$gw['name'] ?? '',
					( $gw['success_count'] ?? 0 ) . '/' . (int) ( $gw['count'] ?? 0 ),
					( $gw['success_rate'] ?? 0 ) . '%',
					$this->format_multi_currency( $gw['success_amounts'] ?? [] ),
				];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R', 'R' ] );
		}

		$trend = $data['trend'] ?? [];
		if ( ! empty( $trend ) ) {
			$this->render_section_title( __( 'Revenue Trend', 'knit-pay-lang' ) );
			$headers = [ __( 'Period', 'knit-pay-lang' ), __( 'Revenue', 'knit-pay-lang' ), __( 'Payments', 'knit-pay-lang' ), __( 'Success Rate', 'knit-pay-lang' ) ];
			$rows    = [];
			$widths  = [ 40, 50, 40, 50 ];
			foreach ( $trend as $period => $info ) {
				$rows[] = [
					$info['period_label'] ?? (string) $period,
					$this->format_multi_currency( $info['success_amounts'] ?? [] ),
					number_format( (int) ( $info['count'] ?? 0 ) ),
					( $info['success_rate'] ?? 0 ) . '%',
				];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R', 'R' ] );
		}
	}

	private function render_transactions( array $data ): void {
		$transactions = $data['transactions'] ?? [];
		$total        = $data['total'] ?? 0;

		$this->SetFont( 'Helvetica', '', 8 );
		$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
		/* translators: 1: Number of payments shown, 2: Total number of payments */
		$this->Cell( 0, 5, sprintf( __( 'Showing %1$d of %2$d payments', 'knit-pay-lang' ), count( $transactions ), $total ), 0, 1 );
		$this->Ln( 2 );

		$headers = [ __( 'ID', 'knit-pay-lang' ), __( 'Status', 'knit-pay-lang' ), __( 'Transaction ID', 'knit-pay-lang' ), __( 'Amount', 'knit-pay-lang' ), __( 'Date', 'knit-pay-lang' ), __( 'Gateway', 'knit-pay-lang' ), __( 'Customer', 'knit-pay-lang' ), __( 'Method', 'knit-pay-lang' ), __( 'Description', 'knit-pay-lang' ) ];
		$widths  = [ 14, 20, 28, 26, 26, 28, 28, 18, 52 ];

		$status_map          = ReportsApiHelper::get_status_map();
		$status_map['trash'] = __( 'Trash', 'knit-pay-lang' );

		$rows = [];
		foreach ( $transactions as $txn ) {
			$amount_str = '';
			$currency   = $txn['currency'] ?? '';
			$amount     = (float) ( $txn['amount'] ?? 0 );
			if ( $currency ) {
				$amount_str = $this->format_currency_amount( $amount, $currency );
			} else {
				$amount_str = number_format( $amount, 2 );
			}

			$rows[] = [
				(string) $txn['id'],
				$status_map[ $txn['status'] ?? '' ] ?? $txn['status'] ?? '',
				$txn['transaction_id'] ?? '',
				$amount_str,
				$txn['date'] ?? '',
				$txn['gateway_name'] ?? '',
				$txn['customer'] ?? '',
				$txn['payment_method_name'] ?? $txn['payment_method'] ?? '',
				$txn['description'] ?? '',
			];
		}

		$this->render_table( $headers, $rows, $widths, [ 'R', 'L', 'L', 'R', 'L', 'L', 'L', 'L', 'L' ] );
	}

	private function render_gateway_performance( array $data ): void {
		if ( empty( $data ) ) {
			$this->SetFont( 'Helvetica', '', 9 );
			$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
			$this->Cell( 0, 8, __( 'No gateway data available.', 'knit-pay-lang' ), 0, 1 );
			return;
		}

		$headers = [ __( 'Gateway', 'knit-pay-lang' ), __( 'Success / Total', 'knit-pay-lang' ), __( 'Success Rate', 'knit-pay-lang' ), __( 'Revenue', 'knit-pay-lang' ), __( 'Volume', 'knit-pay-lang' ) ];
		$rows    = [];
		$widths  = [ 45, 25, 25, 45, 40 ];

		foreach ( $data as $gw ) {
			$rows[] = [
				$gw['name'] ?? '',
				( $gw['success_count'] ?? 0 ) . '/' . (int) ( $gw['count'] ?? 0 ),
				( $gw['success_rate'] ?? 0 ) . '%',
				$this->format_multi_currency( $gw['success_amounts'] ?? [] ),
				$this->format_multi_currency( $gw['amounts'] ?? [] ),
			];
		}

		$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R', 'R', 'R' ] );
	}

	private function render_payment_methods( array $data ): void {
		if ( empty( $data ) ) {
			$this->SetFont( 'Helvetica', '', 9 );
			$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
			$this->Cell( 0, 8, __( 'No payment method data available.', 'knit-pay-lang' ), 0, 1 );
			return;
		}

		$headers = [ __( 'Payment Method', 'knit-pay-lang' ), __( 'Success / Total', 'knit-pay-lang' ), __( 'Success Rate', 'knit-pay-lang' ), __( 'Revenue', 'knit-pay-lang' ), __( 'Volume', 'knit-pay-lang' ) ];
		$rows    = [];
		$widths  = [ 40, 25, 25, 45, 45 ];

		foreach ( $data as $method => $info ) {
			$method_name = ReportsApiHelper::payment_method_name( $method );
			$rows[]      = [
				$method_name,
				( $info['success_count'] ?? 0 ) . '/' . (int) ( $info['count'] ?? 0 ),
				( $info['success_rate'] ?? 0 ) . '%',
				$this->format_multi_currency( $info['success_amounts'] ?? [] ),
				$this->format_multi_currency( $info['amounts'] ?? [] ),
			];
		}

		$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R', 'R', 'R' ] );
	}

	private function render_sources( array $data ): void {
		if ( empty( $data ) ) {
			$this->SetFont( 'Helvetica', '', 9 );
			$this->SetTextColor( ...self::COLOR_TEXT_LIGHT );
			$this->Cell( 0, 8, __( 'No integration data available.', 'knit-pay-lang' ), 0, 1 );
			return;
		}

		$headers = [ __( 'Integration', 'knit-pay-lang' ), __( 'Success / Total', 'knit-pay-lang' ), __( 'Success Rate', 'knit-pay-lang' ), __( 'Revenue', 'knit-pay-lang' ), __( 'Volume', 'knit-pay-lang' ) ];
		$rows    = [];
		$widths  = [ 40, 25, 25, 45, 45 ];

		foreach ( $data as $source => $info ) {
			$rows[] = [
				$info['name'] ?? $source,
				( $info['success_count'] ?? 0 ) . '/' . (int) ( $info['count'] ?? 0 ),
				( $info['success_rate'] ?? 0 ) . '%',
				$this->format_multi_currency( $info['success_amounts'] ?? [] ),
				$this->format_multi_currency( $info['amounts'] ?? [] ),
			];
		}

		$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R', 'R', 'R' ] );
	}

	private function render_refunds( array $data ): void {
		$overview = $data['overview'] ?? [];

		$kpis = [
			[
				'label' => __( 'Total Payments', 'knit-pay-lang' ),
				'value' => number_format( (int) ( $overview['total_count'] ?? 0 ) ),
				'color' => self::COLOR_PRIMARY,
			],
			[
				'label' => __( 'Refunded Payments', 'knit-pay-lang' ),
				'value' => number_format( (int) ( $overview['refunded_count'] ?? 0 ) ),
				'color' => self::COLOR_DANGER,
			],
			[
				'label' => __( 'Refund Rate', 'knit-pay-lang' ),
				'value' => ( $overview['refund_rate'] ?? 0 ) . '%',
				'color' => ( $overview['refund_rate'] ?? 0 ) > 10 ? self::COLOR_DANGER : self::COLOR_WARNING,
			],
			[
				'label' => __( 'Refunded Amount', 'knit-pay-lang' ),
				'value' => $this->format_multi_currency( $overview['refunded_amounts'] ?? [] ),
				'color' => self::COLOR_DANGER,
			],
		];
		$this->render_kpi_cards( $kpis );

		if ( ! empty( $data['by_gateway'] ) ) {
			$this->render_section_title( __( 'Refunds by Gateway', 'knit-pay-lang' ) );
			$headers = [ __( 'Gateway', 'knit-pay-lang' ), __( 'Refunded', 'knit-pay-lang' ), __( 'Amount', 'knit-pay-lang' ) ];
			$rows    = [];
			$widths  = [ 60, 30, 90 ];
			foreach ( $data['by_gateway'] as $gw ) {
				$rows[] = [
					$gw['name'] ?? '',
					number_format( (int) ( $gw['count'] ?? 0 ) ),
					$this->format_multi_currency( $gw['amounts'] ?? [] ),
				];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R' ] );
		}

		if ( ! empty( $data['by_source'] ) ) {
			$this->render_section_title( __( 'Refunds by Source', 'knit-pay-lang' ) );
			$headers = [ __( 'Source', 'knit-pay-lang' ), __( 'Refunded', 'knit-pay-lang' ), __( 'Amount', 'knit-pay-lang' ) ];
			$rows    = [];
			$widths  = [ 60, 30, 90 ];
			foreach ( $data['by_source'] as $src ) {
				$rows[] = [
					$src['name'] ?? '',
					number_format( (int) ( $src['count'] ?? 0 ) ),
					$this->format_multi_currency( $src['amounts'] ?? [] ),
				];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R' ] );
		}

		if ( ! empty( $data['trend'] ) ) {
			$this->render_section_title( __( 'Refund Trend', 'knit-pay-lang' ) );
			$headers = [ __( 'Period', 'knit-pay-lang' ), __( 'Refunds', 'knit-pay-lang' ), __( 'Amount', 'knit-pay-lang' ) ];
			$rows    = [];
			$widths  = [ 50, 30, 100 ];
			foreach ( $data['trend'] as $period => $info ) {
				$rows[] = [
					$info['period_label'] ?? (string) $period,
					number_format( (int) ( $info['count'] ?? 0 ) ),
					$this->format_multi_currency( $info['amounts'] ?? [] ),
				];
			}
			$this->render_table( $headers, $rows, $widths, [ 'L', 'R', 'R' ] );
		}
	}

	private function render_chart_images(): void {
		foreach ( $this->chart_images as $name => $image_data ) {
			if ( empty( $image_data ) || ! is_string( $image_data ) ) {
				continue;
			}

			$prefix = 'data:image/png;base64,';
			if ( 0 !== strpos( $image_data, $prefix ) ) {
				continue;
			}

			$base64 = substr( $image_data, strlen( $prefix ) );
			$binary = base64_decode( $base64, true );
			if ( false === $binary || strlen( $binary ) > 5 * 1024 * 1024 ) {
				continue;
			}

			if ( false === imagecreatefromstring( $binary ) ) {
				continue;
			}

			// wp_tempnam() uses get_temp_dir() internally — the VIP-approved directory.
			// WP_Filesystem direct method writes locally, which FPDF requires for file paths.
			$tmp_path = wp_tempnam( 'kpay-chart.png' );

			try {
				global $wp_filesystem;
				if ( false === $wp_filesystem->put_contents( $tmp_path, $binary ) ) {
					continue;
				}

				$info = getimagesize( $tmp_path );
				if ( false === $info || 'image/png' !== $info['mime'] ) {
					continue;
				}
				$img_w = min( $this->GetPageWidth() - 30, 160 );
				$img_h = $img_w * $info[1] / $info[0];

				$label = ucwords( preg_replace( '/([a-z])([A-Z])/', '$1 $2', str_replace( [ '-', '_' ], ' ', $name ) ) );
				$this->check_page_break( 13 + $img_h + 5 );
				$this->render_section_title( $label );

				$img_y = $this->GetY();
				// Pass explicit 'PNG' type since wp_tempnam() returns a .tmp extension.
				$this->Image( $tmp_path, 15, $img_y, $img_w, $img_h, 'PNG' );
				$this->SetY( $img_y + $img_h + 5 );
			} finally {
				wp_delete_file( $tmp_path );
			}
		}
	}
}
